### ISSUE TITLE
Unnecessary Inheritance of IAlgoMiner in AlgoMiner.sol

### ISSUE THREAD

**Issue by bearcanrun** [Superalgos/ALGOToken#10]
AlgoMiner contract inherits IAlgoMiner but is not intended to and does not call external AlgoMiner instances.  Is the inclusion of the interface superfluous?

https://github.com/Superalgos/ALGOToken/blob/d7530e07578af8bed841470d6520a20cf470198c/labs/algo-token-distribution/src/AdvancedAlgos.AlgoToken.AlgoTokenDistribution/SmartContracts/src/AlgoMiner.sol#L13

**Comment by pmmax** [comment]
IAlgoMiner is used to enforce the correctness of the AlgoMiner functions at compile time, ensuring that they will match the name and signature used when they are called from another contract, for example here https://github.com/Superalgos/ALGOToken/blob/master/labs/algo-token-distribution/src/AdvancedAlgos.AlgoToken.AlgoTokenDistribution/SmartContracts/src/AlgoFees.sol#L36

**Comment by bearcanrun** [comment]
Great, thanks for clarifying the use of interfaces in solidity — the documentation on their use wasn't clear to me. I can see that the [OpenZeppeling ERC20 token](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v2.0.0/contracts/token/ERC20/ERC20.sol) does the same thing.
