### ISSUE TITLE
Provide an error message for require()

### ISSUE THREAD

**Issue by bearcanrun** [Superalgos/ALGOToken#11]
Making use of the error message parameter in require/assert functions can provide meaningful feedback to users.

_Note: This feature request is reinforced by similar action of other large projects in the space like OpenZeppelin/openzeppelin-solidity #888._

_Note2:  This feature is mainly for consumption by client-side dapps. While there are no specific plans in the near future to create a dapp for these contracts, for the purpose of future proofing is another consideration._ 

_Note3: Implementation of consumption by dapps, specifically web3 is still an issue in development as see in ethereum/web3.js #1903._

**Comment by pmmax** [comment]
Well, when I read this the first time I went to the code and completed all "requires" with error messages, but then I carefully read the Note 3, and looking at the issue, I rolled back all changes, since this could be a critical bug, I prefer to do more research before adding those error messages.

**Comment by bearcanrun** [comment]
Agreed, that we should leave it out since it's a feature lacking any form of mature stability.
