### ISSUE TITLE
Examine Private Modifiers

### ISSUE THREAD

**Issue by bearcanrun** [Superalgos/ALGOToken#19]
As contracts are hosted publicly, their code and data do not have privacy. Specifically speaking, the `private` modifier does not make variables invisible. 

This is a due-diligence issue to certify that all `private` modified variables have been examined and do not store critical data.

**Comment by pmmax** [comment]
For these contracts, only the data required for the business logic is included in the contract code, and I understand that is public information. The only way to protect privacy is to encrypt the data, but then this data cannot be used inside the contract for business logic.

But just to ensure this is correct, I'm posting here a summary of the data stored in each contract (taken from the state variables of each contract):

## AlgoFees
* Address of the ERC20 AlgoToken
* List of miners (addresses)
* List of AlgoSystemRole users (addresses)
* List of AlgoCoreTeamRole users (addresses)
* Termination state and creator's address

## AlgoMiner
* Address of the ERC20 AlgoToken
* Miner type (PoolBased, NonPoolBased)
* Miner category
* Miner account address;
* Referral account address;
* Miner state (Deactivated, Activated, Suspended, Stopped)
* Mining state (is mining or not) 
* Current year and day of the mining lifecycle
* Tokens supply for the current year
* List of AlgoSystemRole users (addresses)
* List of AlgoCoreTeamRole users (addresses)
* List of AlgoSupervisorRole users (addresses)
* Termination state and creator's address

## AlgoPool
* Address of the ERC20 AlgoToken
* Pool type (MinerPool, ReferralPool)
* List of funded miners, who already received funds from this pool (addresses)
* List of AlgoCoreTeamRole users (addresses)
* Termination state and creator's address

**Comment by bearcanrun** [comment]
Great! This will be added to the documentation too.
