### ISSUE TITLE
Accomodate leap years

### ISSUE THREAD

**Issue by bearcanrun** [Superalgos/ALGOToken#9]
In the business logic, we need the AlgoMiner to mine on a daily basis, but we don't need to be highly precise as long as the function runs once a day. However, as the contract sits immutable on the block chain, over the course of time, the hardcoded cycle of a year `uint256 public constant DAYS_PER_YEAR = 365;` will become progressively further out of sync with perceived time. 

Is this an issue that should addressed in anyway?

https://github.com/Superalgos/ALGOToken/blob/d7530e07578af8bed841470d6520a20cf470198c/labs/algo-token-distribution/src/AdvancedAlgos.AlgoToken.AlgoTokenDistribution/SmartContracts/src/AlgoMiner.sol#L16

**Comment by pmmax** [comment]
This is by design, by we can check with @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
@bearcanrun can you please give an example ?

**Comment by bearcanrun** [comment]
I'm pretty certain that this is a non-issue, but because it is a contract time-dependency I brought it up for due-diligence.

The argument that it could be an issue is that a leap year adds 1 day every four years or specifically 366 days in a year. What this means in regard to the AlgoMiner contract, is that every four years, it will fall one day behind resulting in a new "fiscal" year starting one day earlier. The only reason this could be a problem is because of the variable _currentYearSupply.
```
# AlgoMiner.sol, L:37-39
    uint8 private _currentYear;
    uint16 private _currentDay;
    uint256 private _currentYearSupply;
```
**Two potential issues:**

1. An accounting issue where every four years one day will be unaccounted for. Another view could be seen, that it's a day that a miner isn't paid — though, this is negated by the contractYearSupply immediately starting over.  
2. After a period of time, the perceivable supply will shift. E.g. in twenty years from 2020, the miner will be starting a new year supply 5 days early.

**Counter-arguments:** 

1. The bottom-line is that the miner gets paid every day and any discrepancies from the accounting side can be dealt with at miner's discretion.
2. The perceivable shift would most likely only be noticed if the contract was deployed precisely on the first day of a new year and an expectation established that a year supply would always last a whole year. Since the contract will most certainly not be deploy on the first day of the year, the shift will not be perceived over time.

I move to close this issue and ask for agreement on  doing so.

**Comment by Luis-Fernando-Molina** [comment]
DAYS_PER_YEAR it is used to know in which year the miner is positioned in order to know where we are positioned from the token distribution schedule point of view. 
It is true that it depends that the contract is executed everyday in order to be in sync with the calendar, but we don't need to worry about that. We will just assume that a _MINING YEAR_ is not a calendar year but 365 executions of the contract.
